name: agent001
services:
  backend:
    container_name: agent001-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=development
      - PORT=3030
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/usr/src/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - redis
  redis:
    container_name: agent001-redis
    image: redis/redis-stack:latest
    ports:
      - "0.0.0.0:6379:6379"
      - "0.0.0.0:3060:8001"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
